In [7]:
# import pandas
import pandas as pd

In [8]:
import os

In [9]:
# function to save modified frames
def save_data_frame(df, filepath):
    df.to_csv(encoding='iso-8859-1', sep=';', path_or_buf=filepath, index=False)

In [117]:
# not working with jupyter
# base_path = os.path.dirname(os.path.realpath(__file__))
base_path = os.path.join(os.getcwd(), 'data')

# operation parameters
#operation = 'filter_missing_values'
operation = 'check_inner_outer_packages'
filename_no_type_postfix = 'ff4-hu-versions9'
file_has_header = None # use 0 for has header and None for does not have a header

raw_path = os.path.join(base_path, 'raw')
modified_path = os.path.join(base_path, 'modified')
# add subdir dropna
modified_path = os.path.join(modified_path, operation)

# hu_versions
hu_versions_headings_path = os.path.join(raw_path, 'ff4-hu-versions0.csv')
hu_versions_raw_path = os.path.join(raw_path, filename_no_type_postfix + '.csv')
hu_versions_modified_path = os.path.join(modified_path, filename_no_type_postfix + '-modified-' + operation + '.csv')

# filter status file path
filter_path = os.path.join(modified_path, 'merged', 'ff4-to-versions-statuses-cleaned-merged-filter_version_statuses.csv')

#exception file path
exception_path = os.path.join(modified_path, 'merged', 'ff4-to-exceptions-merged-filter_version_statuses.csv')

In [118]:
# load file header


hu_versions_frame_headers = pd.read_csv(filepath_or_buffer=hu_versions_headings_path, 
                                header=0, encoding='iso-8859-1', sep=';', nrows = 1)

In [119]:
hu_versions_frame = pd.read_csv(filepath_or_buffer=hu_versions_raw_path, 
                                header=file_has_header, encoding='iso-8859-1', sep=';', names = list(hu_versions_frame_headers))

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (17,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [120]:
# load filter file
filter_frame = pd.read_csv(filepath_or_buffer=filter_path, header=0, encoding='iso-8859-1', sep=';')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [121]:
# load exception code file
exception_frame = pd.read_csv(filepath_or_buffer=exception_path, header=0, encoding='iso-8859-1', sep=';')

In [122]:
# drop every column aside from TO_ID, dwh_TO_Version, p_l_1 and p_l_2
# comments indicate which columns are retained 
hu_versions_frame.drop(['foreign_key',
                        'inet_package_id',
                        #'transportorder_id',
                        #'dwh_transportorder_version',
                        'dwh_masterclient_id',
                        'created_date',
                        'updated_date',
                        'handlingunit_key',
                        #'position_level1',
                        #'position_level2',
                        'quantity',
                        'colli_type',
                        'gross_weight_g',
                        'height_mm',
                        'width_mm',
                        'length_mm',
                        'stackability',
                        'remarks',
                        'description',
                        'barcode',
                        'freight_class',
                        'job_instance_id',
                        'dwh_updated_datetime',], axis=1, inplace= True)

In [123]:
# join filter file
hu_versions_frame = hu_versions_frame.merge(filter_frame, on=['transportorder_id', 'dwh_transportorder_version'], how='inner')

In [124]:
# join exception file
hu_versions_frame = hu_versions_frame.merge(exception_frame, on=['transportorder_id'], how='left')

In [125]:
hu_versions_frame

,transportorder_id,dwh_transportorder_version,position_level1,position_level2,status_date,status_code,issue_type_code
0,VEA13387850,3,1,NaN,2018-03-06 12:50:49,LS130,NaN
1,VEA13387851,3,7,NaN,2018-03-06 12:17:41,LS120,O_CO04
2,VEA13387851,3,7,NaN,2018-03-06 12:17:41,LS120,O_CO05
3,VEA13387851,3,4,NaN,2018-03-06 12:17:41,LS120,O_CO04
4,VEA13387851,3,4,NaN,2018-03-06 12:17:41,LS120,O_CO05
5,VEA13387851,3,2,NaN,2018-03-06 12:17:41,LS120,O_CO04
6,VEA13387851,3,2,NaN,2018-03-06 12:17:41,LS120,O_CO05
7,VEA13387851,3,12,NaN,2018-03-06 12:17:41,LS120,O_CO04
8,VEA13387851,3,12,NaN,2018-03-06 12:17:41,LS120,O_CO05
9,VEA13387851,3,9,NaN,2018-03-06 12:17:41,LS120,O_CO04
10,VEA13387851,3,9,NaN,2018-03-06 12:17:41,LS120,O_CO05
11,VEA13387851,3,1,NaN,2018-03-06 12:17:41,LS120,O_CO04
12,VEA13387851,3,1,NaN,2018-03-06 12:17:41,LS120,O_CO05
13,VEA13387851,3,14,NaN,2018-03-06 12:17:41,LS120,O_CO04
14,VEA13387851,3,14,NaN,2018-03-06 12:17:41,LS120,O_CO05
15,VEA13387851,3,11,NaN,2018-03-06 12:17:41,LS120,O_CO04
16,VEA13387851,3,11,NaN,2018-03-06 12:17:41,LS120,O_CO05
17,VEA13387851,3,6,NaN,2018-03-06 12:17:41,LS120,O_CO04
18,VEA13387851,3,6,NaN,2018-03-06 12:17:41,LS120,O_CO05
19,VEA13387851,3,3,NaN,2018-03-06 12:17:41,LS120,O_CO04
20,VEA13387851,3,3,NaN,2018-03-06 12:17:41,LS120,O_CO05
21,VEA13387851,3,13,NaN,2018-03-06 12:17:41,LS120,O_CO04
22,VEA13387851,3,13,NaN,2018-03-06 12:17:41,LS120,O_CO05
23,VEA13387851,3,10,NaN,2018-03-06 12:17:41,LS120,O_CO04
24,VEA13387851,3,10,NaN,2018-03-06 12:17:41,LS120,O_CO05
25,VEA13387851,3,8,NaN,2018-03-06 12:17:41,LS120,O_CO04
26,VEA13387851,3,8,NaN,2018-03-06 12:17:41,LS120,O_CO05
27,VEA13387851,3,5,NaN,2018-03-06 12:17:41,LS120,O_CO04
28,VEA13387851,3,5,NaN,2018-03-06 12:17:41,LS120,O_CO05
29,VEA13387852,3,1,NaN,2018-03-06 12:50:41,LS130,NaN
...,...,...,...,...,...,...,...
116292,VERX9714315,6,10,NaN,2017-01-09 10:06:32,LS120,NaN
116293,VERX9714315,6,3,NaN,2017-01-09 10:06:32,LS120,NaN
116294,VERX9714315,6,7,NaN,2017-01-09 10:06:32,LS120,NaN
116295,VERX9714315,6,8,NaN,2017-01-09 10:06:32,LS120,NaN
116296,VERX9862444,4,1,NaN,2017-01-23 11:54:24,LS120,NaN
116297,VERX9862444,4,4,NaN,2017-01-23 11:54:24,LS120,NaN
116298,VERX9862444,4,3,NaN,2017-01-23 11:54:24,LS120,NaN
116299,VERX9862444,4,12,NaN,2017-01-23 11:54:24,LS120,NaN
116300,VERX9862444,4,7,NaN,2017-01-23 11:54:24,LS120,NaN
116301,VERX9862444,4,10,NaN,2017-01-23 11:54:24,LS120,NaN
116302,VERX9862444,4,13,NaN,2017-01-23 11:54:24,LS120,NaN
116303,VERX9862444,4,2,NaN,2017-01-23 11:54:24,LS120,NaN
116304,VERX9862444,4,8,NaN,2017-01-23 11:54:24,LS120,NaN
116305,VERX9862444,4,6,NaN,2017-01-23 11:54:24,LS120,NaN
116306,VERX9862444,4,9,NaN,2017-01-23 11:54:24,LS120,NaN
116307,VERX9862444,4,5,NaN,2017-01-23 11:54:24,LS120,NaN
116308,VERX9862444,4,14,NaN,2017-01-23 11:54:24,LS120,NaN
116309,VERX9862444,4,11,NaN,2017-01-23 11:54:24,LS120,NaN
116310,VERX9942439,3,4,NaN,2017-01-30 10:12:52,LS120,NaN
116311,VERX9942439,3,5,NaN,2017-01-30 10:12:52,LS120,NaN
116312,VERX9942439,3,12,NaN,2017-01-30 10:12:52,LS120,NaN
116313,VERX9942439,3,9,NaN,2017-01-30 10:12:52,LS120,NaN
116314,VERX9942439,3,7,NaN,2017-01-30 10:12:52,LS120,NaN
116315,VERX9942439,3,3,NaN,2017-01-30 10:12:52,LS120,NaN
116316,VERX9942439,3,1,NaN,2017-01-30 10:12:52,LS120,NaN
116317,VERX9942439,3,2,NaN,2017-01-30 10:12:52,LS120,NaN
116318,VERX9942439,3,6,NaN,2017-01-30 10:12:52,LS120,NaN
116319,VERX9942439,3,11,NaN,2017-01-30 10:12:52,LS120,NaN
116320,VERX9942439,3,10,NaN,2017-01-30 10:12:52,LS120,NaN
116321,VERX9942439,3,8,NaN,2017-01-30 10:12:52,LS120,NaN

In [126]:
# write result to file
save_data_frame(df=hu_versions_frame,filepath=hu_versions_modified_path)

In [127]:
import glob

In [128]:
# after all file fragments are processed, merge and process further
allFiles = glob.glob(modified_path + "/ff4-hu-versions*.csv")
# default data frame
frame = pd.DataFrame()

# list to contain all data frames to join
list_ = []
for file_ in allFiles:
    df = pd.read_csv(filepath_or_buffer=file_, 
                     header=0, encoding='iso-8859-1', sep=';')
    list_.append(df)
frame = pd.concat(list_, ignore_index=True)

In [129]:
frame

,dwh_transportorder_version,issue_type_code,position_level1,position_level2,status_code,status_date,transportorder_id
0,9.0,NaN,1.0,NaN,LS120,2015-03-24 09:26:40,10000930
1,6.0,NaN,1.0,NaN,LS120,2015-06-03 08:18:04,10001521
2,6.0,NaN,1.0,NaN,LS120,2015-02-16 11:06:47,10001898
3,6.0,NaN,2.0,NaN,LS120,2015-07-21 10:31:29,10002897
4,6.0,NaN,1.0,NaN,LS120,2015-07-21 10:31:29,10002897
5,7.0,NaN,1.0,NaN,LS120,2015-02-03 16:09:00,10003597
6,7.0,NaN,4.0,NaN,LS120,2015-02-03 16:09:00,10003597
7,7.0,NaN,5.0,NaN,LS120,2015-02-03 16:09:00,10003597
8,7.0,NaN,6.0,NaN,LS120,2015-02-03 16:09:00,10003597
9,7.0,NaN,2.0,NaN,LS120,2015-02-03 16:09:00,10003597
10,7.0,NaN,7.0,NaN,LS120,2015-02-03 16:09:00,10003597
11,7.0,NaN,3.0,NaN,LS120,2015-02-03 16:09:00,10003597
12,5.0,NaN,1.0,NaN,LS120,2015-01-30 14:18:13,10004219
13,5.0,NaN,2.0,NaN,LS120,2015-01-30 14:18:13,10004219
14,3.0,NaN,1.0,NaN,LS120,2015-01-30 14:27:55,10004223
15,4.0,NaN,2.0,NaN,LS130,2015-01-30 16:26:29,10004226
16,4.0,NaN,1.0,NaN,LS130,2015-01-30 16:26:29,10004226
17,3.0,NaN,1.0,NaN,LS120,2015-01-30 14:38:52,10004227
18,3.0,NaN,1.0,NaN,LS120,2015-01-30 14:59:59,10004228
19,3.0,NaN,1.0,NaN,LS120,2015-01-30 15:22:10,10004229
20,3.0,NaN,1.0,NaN,LS120,2015-01-30 17:21:34,10004230
21,6.0,NaN,1.0,NaN,LS120,2015-02-02 07:02:50,10004231
22,3.0,NaN,1.0,NaN,LS120,2015-02-02 07:54:41,10004233
23,3.0,NaN,1.0,NaN,LS120,2015-02-02 08:18:26,10004234
24,3.0,NaN,1.0,NaN,LS120,2015-02-02 08:32:58,10004235
25,3.0,NaN,1.0,NaN,LS120,2015-02-02 08:45:17,10004236
26,3.0,NaN,1.0,NaN,LS120,2015-02-02 09:01:04,10004237
27,5.0,NaN,1.0,NaN,LS120,2015-02-02 09:02:57,10004238
28,5.0,NaN,2.0,NaN,LS120,2015-02-02 09:02:57,10004238
29,3.0,NaN,1.0,NaN,LS120,2015-02-02 09:10:25,10004239
...,...,...,...,...,...,...,...
911219,6.0,NaN,10.0,NaN,LS120,2017-01-09 10:06:32,VERX9714315
911220,6.0,NaN,3.0,NaN,LS120,2017-01-09 10:06:32,VERX9714315
911221,6.0,NaN,7.0,NaN,LS120,2017-01-09 10:06:32,VERX9714315
911222,6.0,NaN,8.0,NaN,LS120,2017-01-09 10:06:32,VERX9714315
911223,4.0,NaN,1.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911224,4.0,NaN,4.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911225,4.0,NaN,3.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911226,4.0,NaN,12.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911227,4.0,NaN,7.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911228,4.0,NaN,10.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911229,4.0,NaN,13.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911230,4.0,NaN,2.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911231,4.0,NaN,8.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911232,4.0,NaN,6.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911233,4.0,NaN,9.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911234,4.0,NaN,5.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911235,4.0,NaN,14.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911236,4.0,NaN,11.0,NaN,LS120,2017-01-23 11:54:24,VERX9862444
911237,3.0,NaN,4.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911238,3.0,NaN,5.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911239,3.0,NaN,12.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911240,3.0,NaN,9.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911241,3.0,NaN,7.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911242,3.0,NaN,3.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911243,3.0,NaN,1.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911244,3.0,NaN,2.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911245,3.0,NaN,6.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911246,3.0,NaN,11.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911247,3.0,NaN,10.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439
911248,3.0,NaN,8.0,NaN,LS120,2017-01-30 10:12:52,VERX9942439

In [130]:
# write result to file
save_data_frame(df=frame,
                filepath=os.path.join(modified_path, 'merged', filename_no_type_postfix[:-1] + '-merged-' + operation + '.csv'))

In [63]:
#def convert_hu_into_to(data_frame, groupby_cols, *cols_to_list):
#    data_frame = data_frame.groupby(groupby_cols)['quantity', 'height_mm', 'width_mm', 'length_mm'].agg({'quantity': list}).reset_index()
#    print(data_frame)

In [64]:
#convert_hu_into_to(hu_versions_frame, ['transportorder_id', 'dwh_transportorder_version', 'position_level1', 'gross_weight_g', 'stackability'], 
#                   'quantity', 'height_mm', 'width_mm', 'length_mm')

In [65]:
# show unique values for fields that have to be ecvaluated whether they should be dropped or not
#for series in hu_versions_frame:
#    print('#####\n', series, '\n',hu_versions_frame[series].unique(), '\ncount:' ,len(hu_versions_frame[series].unique()))

In [66]:
# check how many TOs do have more than 1 outer package on position level 1
#hu_versions_frame.loc[(hu_versions_frame['position_level1'] <= 2)].reset_index()

In [67]:
# 10040910, one particular TO with A LOT of outer packages
#hu_versions_frame_temp.loc[(hu_versions_frame['transportorder_id'] == 10040910)].reset_index()