In [1]:
# import pandas
import pandas as pd

In [2]:
import os

In [3]:
# not working with jupyter
# base_path = os.path.dirname(os.path.realpath(__file__))
base_path = os.path.join(os.getcwd(), 'data')

# operation parameters
operation = 'filter_version_statuses'

modified_path = os.path.join(base_path, 'modified')
# add subdir 
modified_path = os.path.join(modified_path, operation)

# add subdir merged
modified_path = os.path.join(modified_path, 'merged')

# hu_versions
hu_versions_modified_path = os.path.join(modified_path, 'ff4-hu-versions-merged-' + operation + '.csv')

# to_exceptions
to_exceptions_modified_path = os.path.join(modified_path, 'ff4-to-exceptions-merged-' + operation + '.csv')

# to_versions
to_versions_modified_path = os.path.join(modified_path, 'ff4-to-versions-c0leaned-merged-' + operation + '.csv')

# to_version_statuses
#to_version_statuses_modified_path = os.path.join(modified_path, 'ffc-to-version-statuses-cleaned-merged-' + operation + '.csv')

In [4]:
# load all files to data frames

hu_versions_frame = pd.read_csv(filepath_or_buffer=hu_versions_modified_path, 
                                header=0, encoding='iso-8859-1', sep=';')
to_exceptions_frame = pd.read_csv(filepath_or_buffer=to_exceptions_modified_path, 
                                  header=0, encoding='iso-8859-1', sep=';')
to_versions_frame = pd.read_csv(filepath_or_buffer=to_versions_modified_path, 
                                header=0, encoding='iso-8859-1', sep=';')
#to_version_statuses_frame = pd.read_csv(filepath_or_buffer=to_version_statuses_raw_path, 
#                                        header=0, encoding='iso-8859-1', sep=';')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
to_versions_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056012 entries, 0 to 1056011
Data columns (total 16 columns):
transportorder_id         1056012 non-null object
created_date              1056012 non-null object
updated_date              1056012 non-null object
incoterm                  1033328 non-null object
owner_company_key         1056012 non-null object
consignor_location_key    1055989 non-null object
recipient_location_key    1055993 non-null object
pickup_date_from          1056012 non-null object
pickup_date_to            1056012 non-null object
delivery_date_from        1056012 non-null object
delivery_date_to          1056012 non-null object
steering_partner_id       488847 non-null object
pickup_location_key       1056012 non-null object
delivery_location_key     1056012 non-null object
status_date               1056012 non-null object
status_code               1056012 non-null object
dtypes: object(16)
memory usage: 128.9+ MB

In [20]:
# HU versions: count how many TOs have at least 2 outer packages and how many TOs have at least one inner package
print('number of TOs in hu-versions:', len(hu_versions_frame['transportorder_id'].unique()))
print('number of TOs with at least 2 outer packages in hu-versions:', 
      len(hu_versions_frame.loc[hu_versions_frame['position_level1'] == 2]['transportorder_id'].unique()))
print('number of TOs with nested inner packages in hu-versions:', 
      len(hu_versions_frame.loc[~pd.isnull(hu_versions_frame['position_level2'])]['transportorder_id'].unique()))
print('number of TOs with multiple outer AND nested inner packages in hu-versions:', 
      len(hu_versions_frame.loc[(hu_versions_frame['position_level1'] == 2)
                                & (~pd.isnull(hu_versions_frame['position_level2']))
                               ]['transportorder_id'].unique()))

number of TOs in hu-versions: 532533
number of TOs with at least 2 outer packages in hu-versions: 130298
number of TOs with nested inner packages in hu-versions: 1116
number of TOs with multiple outer AND nested inner packages in hu-versions: 399

In [21]:
# inspect some of the TOs with more than one outer package and nested packages
hu_versions_frame.loc[hu_versions_frame['transportorder_id'].isin(
hu_versions_frame.loc[(hu_versions_frame['position_level1'] == 2)
                     & (~pd.isnull(hu_versions_frame['position_level2']))
                     ]['transportorder_id'].values)]

,transportorder_id,position_level1,position_level2,quantity,colli_type,gross_weight_g,height_mm,width_mm,length_mm,stackability
5427,10009031,4.0,1.0,5.0,CLL,NaN,170.0,300.0,400.0,NaN
5428,10009031,1.0,1.0,120.0,CLL,NaN,170.0,300.0,400.0,NaN
5429,10009031,2.0,1.0,48.0,CLL,NaN,280.0,300.0,400.0,NaN
5430,10009031,3.0,1.0,24.0,CLL,NaN,280.0,300.0,400.0,NaN
5431,10009031,4.0,NaN,1.0,CLL,44000.0,1100.0,800.0,1200.0,2.0
5432,10009031,1.0,NaN,3.0,CLL,1035000.0,1100.0,800.0,1200.0,2.0
5433,10009031,3.0,NaN,1.0,CLL,600000.0,1100.0,800.0,1200.0,2.0
5434,10009031,2.0,NaN,1.0,CLL,1200000.0,1100.0,800.0,1200.0,2.0
11908,10014559,6.0,NaN,1.0,NaN,157000.0,300.0,800.0,1200.0,2.0
11909,10014559,5.0,NaN,1.0,NaN,600000.0,1100.0,800.0,1200.0,2.0
11910,10014559,4.0,NaN,1.0,NaN,285000.0,1100.0,800.0,1200.0,2.0
11911,10014559,3.0,NaN,2.0,NaN,700000.0,1100.0,800.0,1200.0,2.0
11912,10014559,2.0,NaN,1.0,NaN,260000.0,1100.0,800.0,1200.0,2.0
11913,10014559,1.0,NaN,2.0,NaN,690000.0,1100.0,800.0,1200.0,2.0
11914,10014559,2.0,1.0,40.0,NaN,NaN,170.0,300.0,400.0,NaN
11915,10014559,1.0,1.0,80.0,NaN,NaN,170.0,300.0,400.0,NaN
11916,10014559,4.0,1.0,40.0,NaN,NaN,170.0,300.0,400.0,NaN
11917,10014559,3.0,1.0,80.0,NaN,NaN,170.0,300.0,400.0,NaN
11918,10014559,5.0,1.0,24.0,NaN,NaN,280.0,300.0,400.0,NaN
11919,10014559,6.0,1.0,7.0,NaN,NaN,280.0,300.0,400.0,NaN
17899,10019930,2.0,NaN,2.0,NaN,1200000.0,1100.0,800.0,1200.0,2.0
17900,10019930,3.0,NaN,1.0,NaN,70000.0,300.0,800.0,1200.0,2.0
17901,10019930,1.0,NaN,1.0,CLL,345000.0,1100.0,800.0,1200.0,2.0
17902,10019930,1.0,1.0,40.0,CLL,NaN,170.0,300.0,400.0,NaN
17903,10019930,3.0,1.0,8.0,CLL,NaN,170.0,300.0,400.0,NaN
17904,10019930,2.0,1.0,48.0,CLL,NaN,280.0,300.0,400.0,NaN
23915,10025397,6.0,1.0,2.0,CLL,NaN,1010.0,800.0,1200.0,NaN
23916,10025397,2.0,2.0,1.0,CLL,NaN,490.0,800.0,1200.0,NaN
23917,10025397,4.0,NaN,6.0,CLL,900600.0,1010.0,800.0,1200.0,999.0
23918,10025397,3.0,NaN,3.0,CLL,446700.0,1010.0,800.0,1200.0,999.0
...,...,...,...,...,...,...,...,...,...,...
724695,VE14087037,3.0,1.0,NaN,NaN,NaN,280.0,297.0,396.0,NaN
725888,VE14090160,2.0,NaN,1.0,EUR,747000.0,500.0,800.0,1200.0,1.0
725889,VE14090160,1.0,NaN,1.0,EUR,157000.0,200.0,800.0,1200.0,1.0
725890,VE14090160,2.0,1.0,NaN,NaN,NaN,100.0,200.0,200.0,NaN
725891,VE14090160,1.0,1.0,NaN,NaN,NaN,100.0,200.0,300.0,NaN
727886,VE14106867,5.0,NaN,1.0,PAL,600000.0,1100.0,800.0,1200.0,999.0
727887,VE14106867,1.0,NaN,3.0,PAL,1050000.0,1100.0,800.0,1200.0,999.0
727888,VE14106867,2.0,NaN,2.0,PAL,700000.0,1100.0,800.0,1200.0,999.0
727889,VE14106867,3.0,NaN,2.0,PAL,1200000.0,1100.0,800.0,1200.0,999.0
727890,VE14106867,4.0,NaN,2.0,PAL,1200000.0,1100.0,800.0,1200.0,999.0
727891,VE14106867,1.0,1.0,NaN,NaN,NaN,170.0,300.0,400.0,NaN
727892,VE14106867,2.0,1.0,NaN,NaN,NaN,170.0,300.0,400.0,NaN
727893,VE14106867,6.0,NaN,1.0,EUR,600000.0,1100.0,800.0,1200.0,999.0
727894,VE14106867,7.0,NaN,1.0,EUR,100000.0,1100.0,800.0,1200.0,999.0
727895,VE14106867,5.0,1.0,NaN,NaN,NaN,280.0,297.0,396.0,NaN
727896,VE14106867,3.0,1.0,NaN,NaN,NaN,280.0,297.0,396.0,NaN
727897,VE14106867,4.0,1.0,NaN,NaN,NaN,280.0,297.0,396.0,NaN
819192,VEL10510254,2.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
819193,VEL10510254,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
819194,VEL10510254,2.0,NaN,1.0,CLL,136000.0,60.0,600.0,800.0,1.0
819195,VEL10510254,1.0,NaN,1.0,CLL,124000.0,100.0,600.0,800.0,1.0
822123,VEL11471533,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
822124,VEL11471533,2.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
822125,VEL11471533,1.0,NaN,1.0,CLL,234000.0,750.0,600.0,800.0,1.0
822126,VEL11471533,2.0,NaN,1.0,CLL,129000.0,450.0,600.0,800.0,1.0
831160,VEL13083682,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
831161,VEL13083682,2.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
831162,VEL13083682,2.0,2.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
831163,VEL13083682,1.0,NaN,1.0,CLL,180000.0,1050.0,400.0,800.0,1.0
831164,VEL13083682,2.0,NaN,1.0,CLL,164000.0,600.0,400.0,800.0,1.0

In [22]:
# modifications on hu_versions_frame
# filter for TO's that do only have ONE outer package 
# inspect records that will be dropped first
hu_versions_frame.loc[hu_versions_frame['transportorder_id'].isin(
        hu_versions_frame.loc[hu_versions_frame['position_level1'] == 2]['transportorder_id'].values)]

,transportorder_id,position_level1,position_level2,quantity,colli_type,gross_weight_g,height_mm,width_mm,length_mm,stackability
3,10002897,2.0,NaN,2.0,NaN,514000.0,600.0,800.0,1200.0,3.0
4,10002897,1.0,NaN,2.0,NaN,631000.0,1000.0,800.0,1200.0,3.0
5,10003597,1.0,NaN,1.0,CLL,9000.0,300.0,330.0,410.0,1.0
6,10003597,4.0,NaN,1.0,CLL,5000.0,145.0,310.0,385.0,1.0
7,10003597,5.0,NaN,1.0,CLL,1000.0,125.0,235.0,315.0,1.0
8,10003597,6.0,NaN,1.0,CLL,3000.0,180.0,265.0,265.0,1.0
9,10003597,2.0,NaN,1.0,CLL,10000.0,165.0,390.0,600.0,1.0
10,10003597,7.0,NaN,1.0,CLL,6000.0,245.0,260.0,345.0,1.0
11,10003597,3.0,NaN,1.0,CLL,14000.0,310.0,350.0,460.0,1.0
12,10004219,1.0,NaN,5.0,NaN,2000000.0,1000.0,800.0,1200.0,999.0
13,10004219,2.0,NaN,10.0,NaN,5000000.0,970.0,835.0,1240.0,1.0
15,10004226,2.0,NaN,9.0,NaN,900000.0,984.0,800.0,1210.0,999.0
16,10004226,1.0,NaN,3.0,CLL,450000.0,1024.0,800.0,1210.0,999.0
27,10004238,1.0,NaN,4.0,CLL,400000.0,980.0,830.0,1230.0,2.0
28,10004238,2.0,NaN,1.0,CLL,85000.0,980.0,830.0,1230.0,2.0
30,10004240,2.0,NaN,2.0,NaN,490000.0,1100.0,800.0,1210.0,999.0
31,10004240,1.0,NaN,1.0,CLL,180000.0,880.0,800.0,1210.0,999.0
34,10004243,1.0,NaN,1.0,CLL,107000.0,850.0,800.0,1200.0,1.0
35,10004243,2.0,NaN,1.0,CLL,211000.0,1300.0,800.0,1200.0,1.0
49,10004257,1.0,NaN,10.0,NaN,4000000.0,1200.0,800.0,1200.0,1.0
50,10004257,2.0,NaN,5.0,NaN,2500000.0,700.0,600.0,1000.0,999.0
51,10004258,1.0,NaN,48.0,CLL,3026000.0,950.0,800.0,1210.0,999.0
52,10004258,2.0,NaN,16.0,NaN,1360000.0,970.0,835.0,1240.0,999.0
57,10004263,4.0,NaN,1.0,CLL,225000.0,1330.0,800.0,1200.0,1.0
58,10004263,3.0,NaN,1.0,CLL,210000.0,1060.0,800.0,1200.0,1.0
59,10004263,2.0,NaN,1.0,CLL,190000.0,900.0,800.0,1200.0,1.0
60,10004263,17.0,NaN,1.0,CLL,165000.0,1330.0,800.0,1200.0,1.0
61,10004263,16.0,NaN,1.0,CLL,155000.0,900.0,800.0,1200.0,1.0
62,10004263,15.0,NaN,1.0,CLL,175000.0,1150.0,800.0,1200.0,1.0
63,10004263,14.0,NaN,1.0,CLL,195000.0,1330.0,800.0,1200.0,1.0
...,...,...,...,...,...,...,...,...,...,...
896355,VERX9714315,10.0,NaN,1.0,PAL,315200.0,1090.0,800.0,1200.0,1.0
896356,VERX9714315,3.0,NaN,9.0,CLL,4552200.0,1020.0,974.0,1140.0,1.0
896357,VERX9714315,7.0,NaN,1.0,CLL,429800.0,1020.0,974.0,1140.0,1.0
896358,VERX9714315,8.0,NaN,1.0,CLL,430200.0,1020.0,974.0,1140.0,1.0
896359,VERX9862444,1.0,NaN,1.0,PAL,315000.0,1050.0,800.0,1200.0,1.0
896360,VERX9862444,4.0,NaN,3.0,PAL,1183800.0,950.0,800.0,1200.0,1.0
896361,VERX9862444,3.0,NaN,1.0,PAL,314000.0,1050.0,800.0,1200.0,1.0
896362,VERX9862444,12.0,NaN,5.0,PAL,1577000.0,1050.0,800.0,1200.0,1.0
896363,VERX9862444,7.0,NaN,1.0,PAL,315600.0,1050.0,800.0,1200.0,1.0
896364,VERX9862444,10.0,NaN,1.0,PAL,394000.0,950.0,800.0,1200.0,1.0
896365,VERX9862444,13.0,NaN,1.0,PAL,394000.0,950.0,800.0,1200.0,1.0
896366,VERX9862444,2.0,NaN,1.0,PAL,345800.0,950.0,800.0,1200.0,1.0
896367,VERX9862444,8.0,NaN,5.0,PAL,1579000.0,1050.0,800.0,1200.0,1.0
896368,VERX9862444,6.0,NaN,1.0,CLL,262800.0,580.0,974.0,1140.0,1.0
896369,VERX9862444,9.0,NaN,1.0,CLL,428600.0,1020.0,974.0,1140.0,1.0
896370,VERX9862444,5.0,NaN,1.0,CLL,264600.0,580.0,974.0,1140.0,1.0
896371,VERX9862444,14.0,NaN,2.0,CLL,1010800.0,1020.0,974.0,1140.0,1.0
896372,VERX9862444,11.0,NaN,7.0,CLL,3534400.0,1020.0,974.0,1140.0,1.0
896373,VERX9942439,4.0,NaN,2.0,PAL,788600.0,150.0,800.0,1200.0,1.0
896374,VERX9942439,5.0,NaN,3.0,PAL,1180800.0,150.0,800.0,1200.0,1.0
896375,VERX9942439,12.0,NaN,3.0,PAL,947800.0,1090.0,800.0,1200.0,1.0
896376,VERX9942439,9.0,NaN,6.0,PAL,1935600.0,1090.0,800.0,1200.0,1.0
896377,VERX9942439,7.0,NaN,1.0,PAL,353800.0,150.0,800.0,1200.0,1.0
896378,VERX9942439,3.0,NaN,1.0,PAL,315400.0,1090.0,800.0,1200.0,1.0
896379,VERX9942439,1.0,NaN,1.0,PAL,343600.0,150.0,800.0,1200.0,1.0
896380,VERX9942439,2.0,NaN,1.0,PAL,315000.0,1090.0,800.0,1200.0,1.0
896381,VERX9942439,6.0,NaN,3.0,CLL,1516600.0,1020.0,974.0,1140.0,1.0
896382,VERX9942439,11.0,NaN,3.0,CLL,1292000.0,1020.0,974.0,1140.0,1.0
896383,VERX9942439,10.0,NaN,4.0,CLL,1722000.0,1020.0,974.0,1140.0,1.0
896384,VERX9942439,8.0,NaN,1.0,CLL,249800.0,580.0,974.0,1140.0,1.0

In [23]:
# now filter the frame accordingly
hu_versions_frame = hu_versions_frame.loc[~hu_versions_frame['transportorder_id'].isin(
        hu_versions_frame.loc[Fu]['transportorder_id'].values)]

In [24]:
# FOR NOW: apply the same to inner/nested packages
# filter for TO's that do only have ONE outer package 
# inspect records that will be dropped first
hu_versions_frame.loc[hu_versions_frame['transportorder_id'].isin(
        hu_versions_frame.loc[~pd.isnull(hu_versions_frame['position_level2'])]['transportorder_id'].values)]

,transportorder_id,position_level1,position_level2,quantity,colli_type,gross_weight_g,height_mm,width_mm,length_mm,stackability
90,10004276,1.0,3.0,864.0,CLL,NaN,60.0,260.0,340.0,NaN
91,10004276,1.0,1.0,18.0,CLL,NaN,150.0,800.0,1200.0,NaN
92,10004276,1.0,4.0,18.0,CLL,NaN,90.0,800.0,1200.0,NaN
93,10004276,1.0,2.0,864.0,CLL,NaN,147.0,297.0,396.0,NaN
94,10004276,1.0,NaN,18.0,CLL,3780000.0,1000.0,800.0,1200.0,2.0
95,10004277,1.0,3.0,864.0,CLL,NaN,60.0,260.0,340.0,NaN
96,10004277,1.0,1.0,18.0,CLL,NaN,150.0,800.0,1200.0,NaN
97,10004277,1.0,4.0,18.0,CLL,NaN,90.0,800.0,1200.0,NaN
98,10004277,1.0,2.0,864.0,CLL,NaN,147.0,297.0,396.0,NaN
99,10004277,1.0,NaN,18.0,CLL,3780000.0,1000.0,800.0,1200.0,2.0
518,10004673,1.0,3.0,864.0,CLL,NaN,60.0,260.0,340.0,NaN
519,10004673,1.0,1.0,18.0,CLL,NaN,150.0,800.0,1200.0,NaN
520,10004673,1.0,4.0,18.0,CLL,NaN,90.0,800.0,1200.0,NaN
521,10004673,1.0,2.0,864.0,CLL,NaN,147.0,297.0,396.0,NaN
522,10004673,1.0,NaN,18.0,CLL,3780000.0,1000.0,800.0,1200.0,2.0
610,10004741,1.0,3.0,32.0,CLL,NaN,60.0,260.0,340.0,NaN
611,10004741,1.0,1.0,1.0,CLL,NaN,150.0,800.0,1200.0,NaN
612,10004741,1.0,4.0,1.0,CLL,NaN,90.0,800.0,1200.0,NaN
613,10004741,1.0,2.0,32.0,CLL,NaN,147.0,297.0,396.0,NaN
614,10004741,1.0,NaN,1.0,CLL,140000.0,1000.0,800.0,1200.0,2.0
746,10004873,1.0,3.0,48.0,CLL,NaN,60.0,260.0,340.0,NaN
747,10004873,1.0,1.0,1.0,CLL,NaN,150.0,800.0,1200.0,NaN
748,10004873,1.0,4.0,1.0,CLL,NaN,90.0,800.0,1200.0,NaN
749,10004873,1.0,2.0,48.0,CLL,NaN,147.0,297.0,396.0,NaN
750,10004873,1.0,NaN,1.0,CLL,215000.0,1000.0,800.0,1200.0,2.0
1054,10005126,1.0,3.0,672.0,CLL,NaN,60.0,260.0,340.0,NaN
1055,10005126,1.0,1.0,14.0,CLL,NaN,150.0,800.0,1200.0,NaN
1056,10005126,1.0,4.0,14.0,CLL,NaN,90.0,800.0,1200.0,NaN
1057,10005126,1.0,2.0,672.0,CLL,NaN,147.0,297.0,396.0,NaN
1058,10005126,1.0,NaN,14.0,CLL,3010000.0,1000.0,800.0,1200.0,2.0
...,...,...,...,...,...,...,...,...,...,...
832997,VEL13497284,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
832998,VEL13497284,1.0,2.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
832999,VEL13497284,1.0,NaN,1.0,CLL,150000.0,600.0,400.0,800.0,1.0
833973,VEL13669785,1.0,2.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
833974,VEL13669785,1.0,1.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
833975,VEL13669785,1.0,NaN,1.0,CLL,158000.0,600.0,600.0,800.0,1.0
834430,VEL13758654,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
834431,VEL13758654,1.0,2.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
834432,VEL13758654,1.0,NaN,1.0,CLL,124000.0,450.0,600.0,800.0,1.0
835360,VEL13948694,1.0,1.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
835361,VEL13948694,1.0,2.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
835362,VEL13948694,1.0,NaN,1.0,CLL,218000.0,100.0,600.0,800.0,1.0
835675,VEL14007976,1.0,2.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
835676,VEL14007976,1.0,1.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
835677,VEL14007976,1.0,NaN,1.0,CLL,315000.0,900.0,600.0,800.0,1.0
836015,VEL14073603,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
836016,VEL14073603,1.0,NaN,1.0,CLL,202000.0,750.0,600.0,800.0,1.0
836960,VEL9702871,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
836961,VEL9702871,1.0,NaN,1.0,CLL,95000.0,150.0,600.0,800.0,999.0
836962,VEL9702871,1.0,2.0,NaN,CLL,NaN,20.0,600.0,800.0,NaN
837051,VEL9770117,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
837052,VEL9770117,1.0,NaN,1.0,CLL,124000.0,150.0,600.0,800.0,1.0
837147,VEL9838554,1.0,1.0,NaN,KLT,NaN,147.0,300.0,400.0,NaN
837148,VEL9838554,1.0,NaN,1.0,CLL,170000.0,1500.0,600.0,800.0,1.0
837257,VEL9937552,1.0,2.0,NaN,CLL,NaN,147.0,200.0,300.0,NaN
837258,VEL9937552,1.0,1.0,NaN,CLL,NaN,147.0,300.0,400.0,NaN
837259,VEL9937552,1.0,NaN,1.0,CLL,158000.0,150.0,600.0,800.0,1.0
837364,VEL9983356,1.0,2.0,NaN,KLT,NaN,147.0,200.0,300.0,NaN
837365,VEL9983356,1.0,1.0,NaN,KLT,NaN,147.0,300.0,400.0,NaN
837366,VEL9983356,1.0,NaN,1.0,CLL,56000.0,440.0,600.0,800.0,1.0

In [25]:
# now filter the frame accordingly
hu_versions_frame = hu_versions_frame.loc[~hu_versions_frame['transportorder_id'].isin(
        hu_versions_frame.loc[~pd.isnull(hu_versions_frame['position_level2'])
                             | hu_versions_frame['position_level1'] == 2]['transportorder_id'].values)]

In [26]:
# drop position_level1+2
hu_versions_frame.drop(['position_level1', 'position_level2'], axis=1, inplace=True)

In [72]:
hu_versions_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401618 entries, 0 to 896331
Data columns (total 8 columns):
transportorder_id    401618 non-null object
quantity             401618 non-null float64
colli_type           375632 non-null object
gross_weight_g       401618 non-null float64
height_mm            401618 non-null float64
width_mm             401618 non-null float64
length_mm            401618 non-null float64
stackability         401618 non-null float64
dtypes: float64(6), object(2)
memory usage: 27.6+ MB

In [7]:
# modifications on to_versions_frame
# to preprocess dates
from datetime import datetime

In [8]:
to_versions_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056012 entries, 0 to 1056011
Data columns (total 16 columns):
transportorder_id         1056012 non-null object
created_date              1056012 non-null object
updated_date              1056012 non-null object
incoterm                  1033328 non-null object
owner_company_key         1056012 non-null object
consignor_location_key    1055989 non-null object
recipient_location_key    1055993 non-null object
pickup_date_from          1056012 non-null object
pickup_date_to            1056012 non-null object
delivery_date_from        1056012 non-null object
delivery_date_to          1056012 non-null object
steering_partner_id       488847 non-null object
pickup_location_key       1056012 non-null object
delivery_location_key     1056012 non-null object
status_date               1056012 non-null object
status_code               1056012 non-null object
dtypes: object(16)
memory usage: 128.9+ MB

In [9]:
# format all date time fields as such
to_versions_frame['pickup_date_from'] = pd.to_datetime(to_versions_frame['pickup_date_from'], errors='coerce')
to_versions_frame['pickup_date_to'] = pd.to_datetime(to_versions_frame['pickup_date_to'], errors='coerce')
to_versions_frame['delivery_date_from'] = pd.to_datetime(to_versions_frame['delivery_date_from'], errors='coerce')
to_versions_frame['delivery_date_to'] = pd.to_datetime(to_versions_frame['delivery_date_to'], errors='coerce')
to_versions_frame['status_date'] = pd.to_datetime(to_versions_frame['status_date'], errors='coerce')

In [10]:
to_versions_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056012 entries, 0 to 1056011
Data columns (total 16 columns):
transportorder_id         1056012 non-null object
created_date              1056012 non-null object
updated_date              1056012 non-null object
incoterm                  1033328 non-null object
owner_company_key         1056012 non-null object
consignor_location_key    1055989 non-null object
recipient_location_key    1055993 non-null object
pickup_date_from          1056007 non-null datetime64[ns]
pickup_date_to            1056007 non-null datetime64[ns]
delivery_date_from        1056012 non-null datetime64[ns]
delivery_date_to          1056012 non-null datetime64[ns]
steering_partner_id       488847 non-null object
pickup_location_key       1056012 non-null object
delivery_location_key     1056012 non-null object
status_date               1056012 non-null datetime64[ns]
status_code               1056012 non-null object
dtypes: datetime64[ns](5), object(11)
memory usage: 128.9+ MB

In [11]:
# show records where any datetime value is invalid
to_versions_frame.loc[to_versions_frame['transportorder_id'].isin(
    to_versions_frame.loc[(pd.isnull(to_versions_frame['pickup_date_from']))
                       | (pd.isnull(to_versions_frame['pickup_date_to']))
                       | (pd.isnull(to_versions_frame['delivery_date_from']))
                       | (pd.isnull(to_versions_frame['delivery_date_to']))
                       | (pd.isnull(to_versions_frame['status_date']))]['transportorder_id'].values
)]

,transportorder_id,created_date,updated_date,incoterm,owner_company_key,consignor_location_key,recipient_location_key,pickup_date_from,pickup_date_to,delivery_date_from,delivery_date_to,steering_partner_id,pickup_location_key,delivery_location_key,status_date,status_code
8963,10027061,2016-01-11 13:28:23,2016-01-11 13:31:03,EXW,FF4S001653,198960,TR10,NaT,NaT,2016-01-12 08:00:01,2016-01-12 09:00:59,FF4S001533,198960,TR10,2016-01-11 13:30:52,LS120
39945,10066876,2016-07-26 09:35:03,2016-08-10 09:33:57,FCA,FF4S000402,14823,6580,NaT,NaT,2016-07-29 15:00:01,2016-07-29 17:00:59,FF4S000371,14823,6580,2016-07-26 09:35:03,LS120
53953,10084893,2016-09-30 10:05:54,2016-09-30 11:35:13,FCA,FF4S003715,67363,3626218,NaT,NaT,2016-10-05 10:00:01,2016-10-05 11:00:59,FF4S002816,67363,3626218,2016-09-30 10:06:11,LS120
55810,10087372,2016-10-10 10:48:50,2016-10-10 10:49:34,FCA,FF4S002353,122402,137675,NaT,NaT,2016-10-12 06:00:01,2016-10-12 13:00:59,FF4S001505,122402,137675,2016-10-10 10:48:55,LS120
80669,10120292,2017-01-26 08:47:42,2017-01-26 09:21:56,EXW,FF4S002292,12634,9390,NaT,NaT,2017-02-04 09:00:01,2017-02-04 11:00:59,FF4S001530,12634,9390,2017-01-26 08:55:32,LS120

In [12]:
# filter NAT records
#to_versions_frame = to_versions_frame.loc[~to_versions_frame['transportorder_id'].isin(
#    to_versions_frame.loc[(pd.isnull(to_versions_frame['pickup_date_from']))
#                       | (pd.isnull(to_versions_frame['pickup_date_to']))
#                       | (pd.isnull(to_versions_frame['delivery_date_from']))
#                       | (pd.isnull(to_versions_frame['delivery_date_to']))
#                       | (pd.isnull(to_versions_frame['status_date']))]['transportorder_id'].values
#)]

to_versions_frame.dropna(subset=['pickup_date_from', 
                                 'pickup_date_to', 
                                 'delivery_date_from',
                                 'delivery_date_to',
                                 'status_date'
                                ], axis=0, inplace=True)

In [13]:
# retrieve delivery time and time between issuance of a TO and pickup time

data_frame['delivery_time_seconds'] = 
(data_frame['delivery_date_to']-data_frame['pickup_date_from'])
.apply(lambda x : int(x.seconds + x.days * 24 * 60 * 60))

data_frame['time_to_order_fulfilment_seconds'] = 
(data_frame['pickup_date_from']-data_frame['status_date'])
.apply(lambda x : int(x.seconds + x.days * 24 * 60 * 60))

In [14]:
to_versions_frame[['transportorder_id', 'delivery_time_seconds', 'time_to_order_fulfilment_seconds', 'pickup_date_from', 'status_date']]

,transportorder_id,delivery_time_seconds,time_to_order_fulfilment_seconds,pickup_date_from,status_date
0,10000930,111658,88401,2015-03-25 10:00:01,2015-03-24 09:26:40
1,10001898,91858,8594,2015-02-16 13:30:01,2015-02-16 11:06:47
2,10003597,115258,60661,2015-02-04 09:00:01,2015-02-03 16:09:00
3,10004219,126058,841308,2015-02-09 08:00:01,2015-01-30 14:18:13
4,10004223,223258,408726,2015-02-04 08:00:01,2015-01-30 14:27:55
5,10004226,180058,268412,2015-02-02 19:00:01,2015-01-30 16:26:29
6,10004227,111658,411669,2015-02-04 09:00:01,2015-01-30 14:38:52
7,10004228,298798,338402,2015-02-03 13:00:01,2015-01-30 14:59:59
8,10004229,298798,337071,2015-02-03 13:00:01,2015-01-30 15:22:10
9,10004230,244858,311907,2015-02-03 08:00:01,2015-01-30 17:21:34
10,10004231,504058,107831,2015-02-03 13:00:01,2015-02-02 07:02:50
11,10004233,117058,255920,2015-02-05 07:00:01,2015-02-02 07:54:41
12,10004234,205258,85295,2015-02-03 08:00:01,2015-02-02 08:18:26
13,10004235,271858,98823,2015-02-03 12:00:01,2015-02-02 08:32:58
14,10004236,111658,260084,2015-02-05 09:00:01,2015-02-02 08:45:17
15,10004237,298798,100737,2015-02-03 13:00:01,2015-02-02 09:01:04
16,10004238,97258,104224,2015-02-03 14:00:01,2015-02-02 09:02:57
17,10004239,442858,188376,2015-02-04 13:30:01,2015-02-02 09:10:25
18,10004240,118858,89438,2015-02-03 10:00:01,2015-02-02 09:09:23
19,10004241,223198,89012,2015-02-03 10:00:01,2015-02-02 09:16:29
20,10004242,540058,102792,2015-02-03 14:00:01,2015-02-02 09:26:49
21,10004243,118858,81094,2015-02-03 08:00:01,2015-02-02 09:28:27
22,10004244,151198,73851,2015-02-03 06:00:01,2015-02-02 09:29:10
23,10004245,79258,102392,2015-02-03 14:00:01,2015-02-02 09:33:29
24,10004246,306058,80214,2015-02-03 08:00:01,2015-02-02 09:43:07
25,10004247,320398,76553,2015-02-03 07:00:01,2015-02-02 09:44:08
26,10004248,223198,87245,2015-02-03 10:00:01,2015-02-02 09:45:56
27,10004249,118858,180704,2015-02-04 12:00:01,2015-02-02 09:48:17
28,10004250,117058,78065,2015-02-03 07:30:01,2015-02-02 09:48:56
29,10004251,106258,92275,2015-02-03 11:30:01,2015-02-02 09:52:06
...,...,...,...,...,...
1055982,VERX10516801,849600,-4708,2017-03-10 14:00:00,2017-03-10 15:18:28
1055983,VERX10802626,2115000,251046,2017-04-24 10:30:00,2017-04-21 12:45:54
1055984,VERX10891532,331200,-28100,2017-05-04 14:00:00,2017-05-04 21:48:20
1055985,VERX10914951,511200,664,2017-05-10 13:00:00,2017-05-10 12:48:56
1055986,VERX10933302,2115000,246363,2017-05-15 10:30:00,2017-05-12 14:03:57
1055987,VERX10933303,2115000,246364,2017-05-15 10:30:00,2017-05-12 14:03:56
1055988,VERX10934709,511200,16724,2017-05-15 13:00:00,2017-05-15 08:21:16
1055989,VERX10935673,511200,14563,2017-05-15 13:00:00,2017-05-15 08:57:17
1055990,VERX10952119,331200,9343,2017-05-18 14:00:00,2017-05-18 11:24:17
1055991,VERX10970007,2115000,251621,2017-05-22 10:30:00,2017-05-19 12:36:19
1055992,VERX10978307,244858,9450,2017-05-23 14:00:01,2017-05-23 11:22:31
1055993,VERX10978348,590400,-2193,2017-05-22 14:00:00,2017-05-22 14:36:33
1055994,VERX11019173,849600,-15886,2017-05-26 14:00:00,2017-05-26 18:24:46
1055995,VERX11071560,849600,2984,2017-06-02 14:00:00,2017-06-02 13:10:16
1055996,VERX11071565,849600,893,2017-06-02 14:00:00,2017-06-02 13:45:07
1055997,VERX11104393,511200,-4170,2017-06-09 13:00:00,2017-06-09 14:09:30
1055998,VERX11104721,331200,-89509,2017-06-08 14:00:00,2017-06-09 14:51:49
1055999,VERX11144178,849600,-4368,2017-06-16 14:00:00,2017-06-16 15:12:48
1056000,VERX11168579,2631600,-3811,2017-06-21 11:00:00,2017-06-21 12:03:31
1056001,VERX9207710,331200,8406,2016-12-01 14:00:00,2016-12-01 11:39:54
1056002,VERX9219045,331200,-11400,2016-12-01 14:00:00,2016-12-01 17:10:00
1056003,VERX9411560,511200,9873,2016-12-13 13:00:00,2016-12-13 10:15:27
1056004,VERX9438136,511200,10055,2016-12-14 13:00:00,2016-12-14 10:12:25
1056005,VERX9538098,511200,12198,2016-12-21 13:00:00,2016-12-21 09:36:42
1056006,VERX9580569,511200,14563,2016-12-22 13:00:00,2016-12-22 08:57:17
1056007,VERX9624361,511200,9884,2017-01-03 13:00:00,2017-01-03 10:15:16
1056008,VERX9692533,511200,11814,2017-01-05 13:00:00,2017-01-05 09:43:06
1056009,VERX9714315,511200,10408,2017-01-09 13:00:00,2017-01-09 10:06:32
1056010,VERX9862444,511200,3936,2017-01-23 13:00:00,2017-01-23 11:54:24
1056011,VERX9942439,511200,10028,2017-01-30 13:00:00,2017-01-30 10:12:52

In [15]:
# inspect TO prefixes

to_versions_frame['transportorder_id'].apply(lambda x: str(x)[:4]).unique()

array(['1000', '1001', '1002', '1003', '1004', '1005', '1006', '1007',
       '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015',
       '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1023',
       '1024', '1025', '1026', '1040', 'ME02', 'MEL2', 'VE00', 'VE01',
       'VE02', 'VE03', 'VE04', 'VE05', 'VE06', 'VE07', 'VE08', 'VE09',
       'VE10', 'VE11', 'VE12', 'VE13', 'VE14', 'VEA1', 'VEAX', 'VEL1',
       'VEL2', 'VEL5', 'VEL6', 'VEL7', 'VEL8', 'VEL9', 'VER0', 'VER1',
       'VER2', 'VER3', 'VER5', 'VER6', 'VER7', 'VER8', 'VER9', 'VERX'], dtype=object)

In [16]:
# VERX: how many records would be dropped?
temp = to_versions_frame['transportorder_id'].apply(lambda x: str(x)[:4])
temp.loc[temp == 'VERX']#.apply(lambda x: str(x)[:4]).unique()

1055981    VERX
1055982    VERX
1055983    VERX
1055984    VERX
1055985    VERX
1055986    VERX
1055987    VERX
1055988    VERX
1055989    VERX
1055990    VERX
1055991    VERX
1055992    VERX
1055993    VERX
1055994    VERX
1055995    VERX
1055996    VERX
1055997    VERX
1055998    VERX
1055999    VERX
1056000    VERX
1056001    VERX
1056002    VERX
1056003    VERX
1056004    VERX
1056005    VERX
1056006    VERX
1056007    VERX
1056008    VERX
1056009    VERX
1056010    VERX
1056011    VERX
Name: transportorder_id, dtype: object

In [17]:
to_versions_frame.drop(['status_code', 'status_date'], axis=1, inplace=True)

In [21]:
to_versions_frame.drop(['created_date'], axis=1, inplace=True)

In [22]:
to_versions_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1056007 entries, 0 to 1056011
Data columns (total 13 columns):
transportorder_id         1056007 non-null object
updated_date              1056007 non-null object
incoterm                  1033323 non-null object
owner_company_key         1056007 non-null object
consignor_location_key    1055984 non-null object
recipient_location_key    1055988 non-null object
pickup_date_from          1056007 non-null datetime64[ns]
pickup_date_to            1056007 non-null datetime64[ns]
delivery_date_from        1056007 non-null datetime64[ns]
delivery_date_to          1056007 non-null datetime64[ns]
steering_partner_id       488842 non-null object
pickup_location_key       1056007 non-null object
delivery_location_key     1056007 non-null object
dtypes: datetime64[ns](4), object(9)
memory usage: 112.8+ MB

In [139]:
# modifications on to_exceptions_frame
to_exceptions_frame

      transportorder_id issue_type_code
0            VE12524119          O_CO08
1            VE12456640          O_CO01
2            VE12456609          O_CO01
3              10275018          O_CO01
4              10275018          S_CO08
5            VE12427015          O_CO01
6              10275986          S_CO08
7              10232736          S_CO02
8            VB11926197          O_CO01
9              10232737          S_CO02
10             10275013          O_RE03
11           VB11926172          O_CO01
12           VE11942809          O_RE03
13           VB11926173          O_CO01
14             10012406          O_CO01
15           VB11926174          O_CO01
16             10012439          O_CO07
17           VE11942783          O_CO02
18           VE11942760          O_CR01
19           VE11957421          S_CO03
20             10275881          O_CR02
21           VE11942778          O_CO08
22           VE11942779          O_RE03
23           VB11926180          O_CO01
24             10012438          O_CO01
25           VE11957439          O_CR01
26             10232772          O_RE02
27             10233791          S_CO02
28             10012446          S_CO02
29             10276891          S_CO02
...                 ...             ...
45779       VEA14060863          O_CO02
45780        VE13971503          O_CO05
45781        VE13956006          O_CO05
45782        VE13955210          O_CO01
45783        VE14012508          O_CO05
45784       VEA13996860          O_CO04
45785        VE13955623          O_CO05
45786        VE13782062          O_CR05
45787        VE13956137          O_CR05
45788       VEA14060863          O_CO04
45789        VE13938973          O_HU02
45790        VE13954886          O_CO08
45791        VE13781654          O_CO05
45792        VE13956173          O_CO04
45793        VE13977111          O_CO04
45794        VE13922082          O_CR05
45795        VE13781761          O_CR05
45796        VE14072330          O_CO05
45797        VE13930880          O_CO05
45798        VE13687715          R_4F14
45799       VE14083856           S_RE01
45800        VE13800826          O_RE02
45801        VE14112287          S_CO01
45802        VE13843804          O_CO05
45803        VE13800826          R_4F07
45804        VE14107483          S_CO08
45805        VE13955331          R_4F05
45806        VE13954897          R_4F03
45807        VE13955067          O_CR02
45808       VEA14108026          R_4F01

[45809 rows x 2 columns]

In [140]:
# change according to the desired label rule: 
# current rule: S_CO02 vs. everything else

data_frame['issue_type_code'] = 
data_frame['issue_type_code'].apply(lambda x: 1 if x == 'S_CO02' else 0)

In [141]:
to_exceptions_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45809 entries, 0 to 45808
Data columns (total 2 columns):
transportorder_id    45809 non-null object
issue_type_code      45809 non-null int64
dtypes: int64(1), object(1)
memory usage: 715.8+ KB

In [142]:
# count labels
from collections import Counter

In [143]:
Counter(to_exceptions_frame['issue_type_code'])

Counter({0: 26749, 1: 19060})

In [151]:
# join data frames

merge_df = hu_versions_frame.merge(to_exceptions_frame, on=['transportorder_id'], how='left')
merge_df = merge_df.merge(to_versions_frame, on=['transportorder_id'], how='inner')

In [152]:
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 367480 entries, 0 to 367479
Data columns (total 24 columns):
transportorder_id                   367480 non-null object
quantity                            367480 non-null float64
colli_type                          362437 non-null object
gross_weight_g                      367480 non-null float64
height_mm                           367480 non-null float64
width_mm                            367480 non-null float64
length_mm                           367480 non-null float64
stackability                        367480 non-null float64
issue_type_code                     10907 non-null float64
created_date                        367480 non-null object
updated_date                        367480 non-null object
incoterm                            367423 non-null object
owner_company_key                   367480 non-null object
consignor_location_key              367470 non-null object
recipient_location_key              367466 non-null object
pickup_date_from                    367480 non-null datetime64[ns]
pickup_date_to                      367480 non-null datetime64[ns]
delivery_date_from                  367480 non-null datetime64[ns]
delivery_date_to                    367480 non-null datetime64[ns]
steering_partner_id                 364533 non-null object
pickup_location_key                 367480 non-null object
delivery_location_key               367480 non-null object
delivery_time_seconds               367480 non-null int64
time_to_order_fulfilment_seconds    367480 non-null int64
dtypes: datetime64[ns](4), float64(7), int64(2), object(11)
memory usage: 70.1+ MB

In [ ]:
from collections import Counter

In [ ]:
Counter(merge_df['issue_type_code'])

In [146]:
# fill nan in label column (issue_type_code) to 0
merge_df['issue_type_code'].fillna(value=0, inplace=True)
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 367480 entries, 0 to 367479
Data columns (total 24 columns):
transportorder_id                   367480 non-null object
quantity                            367480 non-null float64
colli_type                          362437 non-null object
gross_weight_g                      367480 non-null float64
height_mm                           367480 non-null float64
width_mm                            367480 non-null float64
length_mm                           367480 non-null float64
stackability                        367480 non-null float64
issue_type_code                     367480 non-null float64
created_date                        367480 non-null object
updated_date                        367480 non-null object
incoterm                            367423 non-null object
owner_company_key                   367480 non-null object
consignor_location_key              367470 non-null object
recipient_location_key              367466 non-null object
pickup_date_from                    367480 non-null datetime64[ns]
pickup_date_to                      367480 non-null datetime64[ns]
delivery_date_from                  367480 non-null datetime64[ns]
delivery_date_to                    367480 non-null datetime64[ns]
steering_partner_id                 364533 non-null object
pickup_location_key                 367480 non-null object
delivery_location_key               367480 non-null object
delivery_time_seconds               367480 non-null int64
time_to_order_fulfilment_seconds    367480 non-null int64
dtypes: datetime64[ns](4), float64(7), int64(2), object(11)
memory usage: 70.1+ MB

In [147]:
# function to save modified frames
def save_data_frame(df, filepath):
    df.to_csv(encoding='iso-8859-1', sep=';', path_or_buf=filepath, index=False)

In [148]:
# save merged df
# use suffix for integer encoded frame
save_data_frame(merge_df, os.path.join(modified_path, 'ff4-all-merged-' + operation + '.csv'))

In [4]:
data_frame = pd.read_csv(filepath_or_buffer=os.path.join(modified_path, 'ff4-all-merged-' + operation + '.csv'), 
                                header=0, encoding='iso-8859-1', sep=';')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [25]:
################################################################################################################################
####                                           actual preprocessing starts here                                             ####
################################################################################################################################

In [5]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367480 entries, 0 to 367479
Data columns (total 24 columns):
transportorder_id                   367480 non-null object
quantity                            367480 non-null float64
colli_type                          362437 non-null object
gross_weight_g                      367480 non-null float64
height_mm                           367480 non-null float64
width_mm                            367480 non-null float64
length_mm                           367480 non-null float64
stackability                        367480 non-null float64
issue_type_code                     367480 non-null float64
created_date                        367480 non-null object
updated_date                        367480 non-null object
incoterm                            367423 non-null object
owner_company_key                   367480 non-null object
consignor_location_key              367470 non-null object
recipient_location_key              367466 non-null object
pickup_date_from                    367480 non-null object
pickup_date_to                      367480 non-null object
delivery_date_from                  367480 non-null object
delivery_date_to                    367480 non-null object
steering_partner_id                 364533 non-null object
pickup_location_key                 367480 non-null object
delivery_location_key               367480 non-null object
delivery_time_seconds               367480 non-null int64
time_to_order_fulfilment_seconds    367480 non-null int64
dtypes: float64(7), int64(2), object(15)
memory usage: 67.3+ MB

In [8]:
data_frame.drop(['created_date'], axis = 1, inplace=True)

In [9]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367480 entries, 0 to 367479
Data columns (total 21 columns):
transportorder_id         367480 non-null object
quantity                  367480 non-null float64
colli_type                362437 non-null object
gross_weight_g            367480 non-null float64
height_mm                 367480 non-null float64
width_mm                  367480 non-null float64
length_mm                 367480 non-null float64
stackability              367480 non-null float64
issue_type_code           367480 non-null float64
updated_date              367480 non-null object
incoterm                  367423 non-null object
owner_company_key         367480 non-null object
consignor_location_key    367470 non-null object
recipient_location_key    367466 non-null object
pickup_date_from          367480 non-null object
pickup_date_to            367480 non-null object
delivery_date_from        367480 non-null object
delivery_date_to          367480 non-null object
steering_partner_id       364533 non-null object
pickup_location_key       367480 non-null object
delivery_location_key     367480 non-null object
dtypes: float64(7), object(14)
memory usage: 58.9+ MB

In [30]:
# to preprocess categorical columns
def one_hot_encode(data_frame, column, nan_naming=False): 
    
    # one hot encoding of the particular series
    temp = pd.get_dummies(data=data_frame[column], dummy_na=nan_naming, prefix=column)
    
    if nan_naming:
        temp.rename(columns={temp.columns[-1]: '{} NaNs'.format(column)}, inplace=True)
        
    # drop the column that's no longer required
    data_frame.drop([column], inplace=True, axis=1)
    # join newly created columns
    data_frame = pd.concat([data_frame, temp], axis=1)
    
    # mandatory return statement
    return data_frame

In [31]:
# alternate way to preprocess to make data easier to handel for hardware
def integer_encode(data_frame, column):
    
    unique_dict = {val: i for i, val in enumerate(list(set(data_frame[column].values)))}
    # print(unique_dict)
    
    # thanks to the set operation above, nan will always be at value 0!
    data_frame[column] = data_frame[column].apply(lambda x: unique_dict.get(x, 0))
    
    return data_frame

In [34]:
import numpy as np

In [36]:
#testing
temp_df = pd.DataFrame({'col1': ['hans', 'peter', 'hans', np.nan]})
print(temp_df)
temp_df = integer_encode(temp_df, 'col1')
print(temp_df)

    col1
0   hans
1  peter
2   hans
3    NaN
{nan: 0, 'peter': 1, 'hans': 2}
   col1
0     2
1     1
2     2
3     0

In [150]:
# iterate over data frame and transform serieses
for series in merge_df:
        # show unique values for fields that have to be ecvaluated whether they should be dropped or not
        print('#####\n', series, '\ncount:' ,len(merge_df[series].unique()))

#####
 transportorder_id
count: 363554
#####
 quantity
count: 162
#####
 colli_type
count: 21
#####
 gross_weight_g
count: 25704
#####
 height_mm
count: 815
#####
 width_mm
count: 342
#####
 length_mm
count: 423
#####
 stackability
count: 99
#####
 issue_type_code
count: 2
#####
 created_date
count: 254385
#####
 updated_date
count: 346044
#####
 incoterm
count: 7
#####
 owner_company_key
count: 2272
#####
 consignor_location_key
count: 2834
#####
 recipient_location_key
count: 1591
#####
 pickup_date_from
count: 43079
#####
 pickup_date_to
count: 41360
#####
 delivery_date_from
count: 42151
#####
 delivery_date_to
count: 44785
#####
 steering_partner_id
count: 117
#####
 pickup_location_key
count: 2743
#####
 delivery_location_key
count: 1577
#####
 delivery_time_seconds
count: 2852
#####
 time_to_order_fulfilment_seconds
count: 166651

In [38]:
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 316850 entries, 0 to 316849
Data columns (total 42 columns):
quantity                            316850 non-null float64
colli_type                          316850 non-null int64
gross_weight_g                      316850 non-null float64
height_mm                           316850 non-null float64
width_mm                            316850 non-null float64
length_mm                           316850 non-null float64
stackability                        316850 non-null float64
incoterm                            316850 non-null int64
pickup_location_key                 316850 non-null int64
delivery_location_key               316850 non-null int64
delivery_time_seconds               316850 non-null int64
label                               316850 non-null float64
created_date DoW                    316850 non-null int64
created_date DoY                    316850 non-null int64
created_date MoY                    316850 non-null int64
created_date HoD                    316850 non-null int64
created_date Absolute Time          316850 non-null float64
updated_date DoW                    316850 non-null int64
updated_date DoY                    316850 non-null int64
updated_date MoY                    316850 non-null int64
updated_date HoD                    316850 non-null int64
updated_date Absolute Time          316850 non-null float64
pickup_date_from DoW                316850 non-null int64
pickup_date_from DoY                316850 non-null int64
pickup_date_from MoY                316850 non-null int64
pickup_date_from HoD                316850 non-null int64
pickup_date_from Absolute Time      316850 non-null float64
pickup_date_to DoW                  316850 non-null int64
pickup_date_to DoY                  316850 non-null int64
pickup_date_to MoY                  316850 non-null int64
pickup_date_to HoD                  316850 non-null int64
pickup_date_to Absolute Time        316850 non-null float64
delivery_date_from DoW              316850 non-null int64
delivery_date_from DoY              316850 non-null int64
delivery_date_from MoY              316850 non-null int64
delivery_date_from HoD              316850 non-null int64
delivery_date_from Absolute Time    316850 non-null float64
delivery_date_to DoW                316850 non-null int64
delivery_date_to DoY                316850 non-null int64
delivery_date_to MoY                316850 non-null int64
delivery_date_to HoD                316850 non-null int64
delivery_date_to Absolute Time      316850 non-null float64
dtypes: float64(13), int64(29)
memory usage: 103.9 MB